### ISSUE TITLE
Readme missing information or extra steps required

### ISSUE THREAD

**Issue by Assambra** [vu-luong/ezy-smashers#44]
There is no hint that the unity package newtonsoft is required or some installation steps for it.

Adding the Newton Json package in Unity via the Package Manager 
Window -> Package Manager -> Plus Sign -> Add package from git URL ->  insert into the URL flield -> com.unity.nuget.newtonsoft-json.

Or edit the manifest.json file in the Packages folder of your Unity project and add "com.unity.nuget.newtonsoft-json": "3.2.1",

**Comment by vu-luong** [comment]
Thank you for raise the issue. I'll update the README in [https://github.com/youngmonkeys/ezyfox-server-csharp-client/tree/unity-client](https://github.com/youngmonkeys/ezyfox-server-csharp-client/tree/unity-client) to include the above steps.
