### ISSUE TITLE
Missing Scripts in prefabs / Login scene

### ISSUE THREAD

**Issue by Assambra** [vu-luong/ezy-smashers#45]
There are missing scripts in the SocketEventProcessor and LoggerConfig prefabs.

Is this correct that the Folder _Project/Scripts/socket is empty? if yes delete the folder meta file of not there are no files maybe the missing files from the prefab?

**Comment by vu-luong** [comment]
Thank you for reporting the issue of missing scripts. It was caused by Unity re-indexing files from the submodule `ezyfox-server-csharp-client`. I have added a section on how to resolve it: https://github.com/vu-luong/ezy-smashers#resolve-missing-scripts

**Comment by Assambra** [comment]
Thank you this solved my issue. But now there is a new issue i can create/join a room but cant move arraound or smash other players.
