### ISSUE TITLE
Cant move around or smash other players

### ISSUE THREAD

**Issue by Assambra** [vu-luong/ezy-smashers#46]
There is a issue i can create/join (sometimes with wired behaviour) a room but cant move around or smash other players.

If i start the second client i get lost ping count warning after 5 warnings ive got following errors.

    I/O error at socket-reader: Ein Blockierungsvorgang wurde durch einen Aufruf von WSACancelBlockingCall unterbrochen.
    I/O error at socket-reader
    System.IO.IOException: Unable to read data from the transport connection: Ein Blockierungsvorgang wurde durch einen Aufruf von WSACancelBlockingCall unterbrochen.

![EzySmashers](https://github.com/vu-luong/ezy-smashers/assets/6276777/87ac6f11-abb2-4f51-be28-08fd1691ea94)

**Comment by Assambra** [comment]
I used the wrong Java version 11 i described here:

https://github.com/youngmonkeys/ezyfox-server/issues/107#issuecomment-1575571359

The errors are gone but cant still move or smash others players any ideas?

**Comment by Assambra** [comment]
In Unity -> Edit -> Project Settings -> Player -> Resolution and Presentation -> Enable, Run in Background
So you can see on other clients the movement.

**Comment by Assambra** [comment]
It would be nice that the rotation of remote character works too, not only for the local player.

**Comment by tvd12** [comment]
So did the problem resolve?

**Comment by Assambra** [comment]
yes, thank you.
